language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - 0.6
notifications:
  email: false
script:
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.test("ApproXD", coverage=true)'
after_success:
  - julia -e 'Pkg.add("Coverage")'
  - julia -e 'cd(Pkg.dir("ApproXD")); using Coverage; Coveralls.submit(process_folder())'
